ARG ROS_DISTRO=jazzy

FROM husarnet/ros:${ROS_DISTRO}-ros-core
SHELL ["/bin/bash", "-c"]

RUN apt update && apt install -y \
        ros-${ROS_DISTRO}-rviz2 \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV LIBGL_ALWAYS_SOFTWARE=1
